__Q. 1.Create a 3x3x3 array with random values__

In [1]:
import numpy as np
x= np.random.random((3,3,3))
print(x)

[[[0.58584003 0.70920152 0.14173388]
  [0.06802003 0.18483627 0.14169138]
  [0.86164132 0.60864638 0.01761535]]

 [[0.45105685 0.77967911 0.59187037]
  [0.2536328  0.51273735 0.27495728]
  [0.50736307 0.30735616 0.77443522]]

 [[0.93383933 0.96639088 0.23267132]
  [0.39135053 0.97661037 0.77370632]
  [0.92261004 0.53076146 0.13538312]]]


__Q.2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal__

In [4]:
z= np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


__Q.3.Create a 8x8 matrix and fill it with a checkerboard pattern__

In [5]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


__Q.4. Normalize a 5x5 random matrix__

In [7]:
z=np.random.random((5,5))
zmax,zmin=z.max(),z.min()
z=(z-zmin/(zmax-zmin))
print(z)

[[ 0.77851507  0.61622936  0.62265005  0.72285338  0.81041274]
 [ 0.03834526 -0.0174841   0.52799437  0.74405824  0.49206386]
 [ 0.31043393  0.19201038  0.19237611  0.17761454  0.31236583]
 [ 0.24947424  0.63872262  0.66205041  0.69336288  0.69132353]
 [ 0.27746657  0.00667809  0.50730625  0.72542717  0.45214998]]


__Q.5. How to find common values between two arrays?__

In [8]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [20, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [20, 30, 40]
Common values between two arrays:
[20 40]


__Q.6.How to get the dates of yesterday, today and tomorrow?__

In [9]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday Date is: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today Date is: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow Date is: ",tomorrow)

Yestraday Date is:  2020-07-24
Today Date is:  2020-07-25
Tomorrow Date is:  2020-07-26


__Q.7. Consider two random array A and B, check if they are equal__

In [86]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 0 1 1 0]
Second array:
[1 1 0 1 1 0]
Test above two arrays are equal or not!
True


__Q.8.Create random vector of size 10 and replace the maximum value by 0__

In [87]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.40635344 0.13219313 0.73473339 0.24795827 0.6835624  0.7311331
 0.42642147 0.69591227 0.84872982 0.09818385]
Maximum value replaced by 0:
[0.40635344 0.13219313 0.73473339 0.24795827 0.6835624  0.7311331
 0.42642147 0.69591227 0.         0.09818385]


__Q.9.How to print all the values of an array in numpy?__

In [94]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

__Q.10.Subtract the mean of each row of a matrix__

In [95]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row :\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.51877087 0.16142351 0.03398506 0.34731956 0.11361582 0.2559225
  0.25590865 0.02738155 0.28826432 0.95465621]
 [0.02614614 0.67512614 0.47343612 0.80951962 0.26521759 0.84651122
  0.66551274 0.72685515 0.99765718 0.0828818 ]
 [0.15835606 0.44389525 0.80994035 0.05831601 0.28891165 0.41730258
  0.75207037 0.59326748 0.68297058 0.05303851]
 [0.58979205 0.98552537 0.84487103 0.9984008  0.25523431 0.2539213
  0.65858324 0.77981722 0.9775555  0.17201166]
 [0.21214925 0.33195403 0.91473398 0.92158622 0.00698711 0.64728979
  0.68702629 0.67145863 0.41085823 0.41194561]]

Subtract the mean of each row :

[[ 0.22304606 -0.13430129 -0.26173975  0.05159476 -0.18210898 -0.03980231
  -0.03981615 -0.26834325 -0.00746048  0.6589314 ]
 [-0.53074023  0.11823977 -0.08345025  0.25263325 -0.29166878  0.28962485
   0.10862637  0.16996878  0.44077081 -0.47400457]
 [-0.26745083  0.01808837  0.38413347 -0.36749088 -0.13689523 -0.0085043
   0.32626349  0.16746059  0.2571637  -0.37276837]


__Q.11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?__

In [125]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 4. 4. 5. 3. 2. 4. 1. 2.]


__Q.12.How to get the diagonal of a dot product?__

In [137]:
J = np.random.randint(0,10,(3,3))
K= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(J, K))

array([45, 61, 92])

__Q.13.How to find the most frequent value in an array?__

In [138]:
z=np.random.randint(0,10,50)
print(z)
print('Most Frequent value is :',np.bincount(z).argmax())

[0 2 6 5 2 2 0 7 7 4 1 0 9 9 4 8 7 1 3 7 3 5 8 2 5 8 9 3 2 3 5 6 5 5 5 3 0
 7 8 3 4 0 5 2 1 3 5 0 0 7]
Most Frequent value is : 5


__Q.14.How to get the n largest values of an array__

In [139]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


__Q.15.How to create a record array from a regular array?__

In [148]:
Z = np.array([("Welcome", 4.6, 7),
              ("Here", 2.9, 3)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print('Record Array: ',R)
print('Regular Arraay: ',Z)

Record Array:  [(b'Welcome', 4.6, 7) (b'Here', 2.9, 3)]
Regular Arraay:  [['Welcome' '4.6' '7']
 ['Here' '2.9' '3']]
